### PR TITLE
Bump to @ory/client 1.0.1

### PR DESCRIPTION
**Pull request by drev74**
## Checklist

- [x] I have read the [contributing guidelines](../blob/master/CONTRIBUTING.md) and signed the CLA.
- [x] I have referenced an issue containing the design document if my change introduces a new feature.
- [ ] I have read the [security policy](../security/policy).
- [ ] I confirm that this pull request does not address a security vulnerability. 
      If this pull request addresses a security vulnerability, 
      I confirm that I got approval (please contact [security@ory.sh](mailto:security@ory.sh)) from the maintainers to push the changes.
- [ ] I have added tests that prove my fix is effective or that my feature works.
- [ ] I have added the necessary documentation within the code base (if appropriate).

### CODE REVIEW

**Comment by drev74** [comment]
@vinckr :eyes:

**Comment by DrBu7cher** [comment]
Could we update this to bump to v1.1.0 right away?

**Review by jonas-jonas — CHANGES_REQUESTED** [review]
Sorry for the late review. A few things need to be updated. And I think you can update to v1.1, AFAIK there were no changes to the frontend.

**Comment by DrBu7cher** [comment]
@jonas-jonas Please have a look at #228
I followed the requested changes from here, bumped to v1.1.0 and also implemented an optional Hydra consent page.

**Comment by Benehiko** [comment]
Hi @drev74 

Thank you that you took the time to work on this, unfortunately we require this repository on the latest sdk and are a bit pressed for time according to our internal roadmap and merged #229

Please do continue to contribute to the Ory community - we really do appreciate it :heart:

**Pull request closed without merging**
