### PR TITLE
feat: Implemented HTTPS support configured using env vars

### PR DESCRIPTION
**Pull request by programmador**
## Related issue

#62 

## Proposed changes

Adds optional TLS_CERT_PATH and TLS_KEY_PATH variables that enable https

## Checklist

- [x] I have read the [contributing guidelines](../blob/master/CONTRIBUTING.md)
- [x] I have read the [security policy](../security/policy)
- [x] I confirm that this pull request does not address a security
      vulnerability. If this pull request addresses a security vulnerability, I
      confirm that I got green light (please contact
      [security@ory.sh](mailto:security@ory.sh)) from the maintainers to push
      the changes.
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] I have added necessary documentation within the code base (if appropriate)

### CODE REVIEW

**Comment by programmador** [comment]
Please don't merge it now. Docker build is failing.
'npm run build' tells that smth wrong is typing while 'npm run start' is working fluently.
I'm not a nodejs developer actually So I can't understand why behaviour differs

**Comment by programmador** [comment]
> Please don't merge it now. Docker build is failing.
> 'npm run build' tells that there is smth wrong with typing while 'npm run start' is working fluently.
> I'm not a nodejs developer actually So I can't understand why behaviour differs

Fixed.

**Comment by aeneasr** [comment]
Nice, thank you! :)

**Comment by programmador** [comment]
You're wellcome!

**Pull request merged**
